site_name: taskcat
site_url: http://taskcat.io
site_description: Project documentation for taskcat python class.

repo_url: https://github.com/aws-quickstart/taskcat

theme: readthedocs

pages:
- Home: index.md

